<a href="https://colab.research.google.com/github/a-forty-two/QA_9_MAY_22_BDML/blob/main/Choosing_the_right_estimator_solved.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Practical Machine Learning 
### Project: Model Selection

# Abstract

# Part 1: Business and Data Understanding

### Q. Define the problem domain

### Q. Identify candidate questions for your machine learning project

### Q. Identify a suitable dataset for your canditate question(s)

Go have a look at any of these websites:

* https://www.kaggle.com/datasets 
* https://datasetsearch.research.google.com/
* https://data.gov.uk/

Find an interesting looking data set related to your problem domain and get a copy of it

In [1]:
!ls

breastcancer_data.csv  sample_data

In [2]:
import pandas as pd
df = pd.read_csv('breastcancer_data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,symmetry_mean,fractal_dimension_mean
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.2419,0.07871
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.1812,0.05667
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.2069,0.05999
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.2597,0.09744
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.1809,0.05883

In [5]:
df.set_index('id', inplace=True)

In [6]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,symmetry_mean,fractal_dimension_mean
id,,,,,,,,,,
842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.2419,0.07871
842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.1812,0.05667
84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.2069,0.05999
84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.2597,0.09744
84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.1809,0.05883

### Q. Generate a descriptive statistics report for the columns in your dataset

In [7]:
df.describe()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,symmetry_mean,fractal_dimension_mean
count,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.181162,0.062798
std,3.522499,4.299144,24.288293,351.759340,0.014058,0.052790,0.079685,0.027402,0.007057
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.106000,0.049960
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.161900,0.057700
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.179200,0.061540
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.195700,0.066120
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.304000,0.097440

# Part 2: Data Preparation

### Q. Discuss the following types of missing data and how they would be handled in reference to your dataset where applicable.
*	Missing completely at random (MCAR)
*	Missing at random (MAR)
*	Missing Not at Random (MNAR)

In [ ]:
# Training-> absent, present during inf-> MNAR
#   -> simulate or generate data
# Production/Inference-> MAT-> Cross-Join
# BOTH-> MCAR -> don't use such columns

In [8]:
# ONLY nums!-> diagnosis! (LABEL)
cancer_dict = {'M': 1, 'B':0}
y = df.pop('diagnosis')
df.head()
# y = weights * df + bias

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,symmetry_mean,fractal_dimension_mean
id,,,,,,,,,
842302,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.2419,0.07871
842517,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.1812,0.05667
84300903,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.2069,0.05999
84348301,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.2597,0.09744
84358402,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.1809,0.05883

In [9]:
# X -> normalized
# Y -> encoded

In [10]:
y_encoded = y.map(lambda label: cancer_dict[label] )
y_encoded.head()

id
842302      1
842517      1
84300903    1
84348301    1
84358402    1
Name: diagnosis, dtype: int64

In [12]:
# Norm
stats = df.describe().T
stats

,count,mean,std,min,25%,50%,75%,max
radius_mean,1138.0,14.127292,3.522499,6.98100,11.70000,13.37000,15.78000,28.11000
texture_mean,1138.0,19.289649,4.299144,9.71000,16.17000,18.84000,21.80000,39.28000
perimeter_mean,1138.0,91.969033,24.288293,43.79000,75.17000,86.24000,104.10000,188.50000
area_mean,1138.0,654.889104,351.759340,143.50000,420.30000,551.10000,782.70000,2501.00000
smoothness_mean,1138.0,0.096360,0.014058,0.05263,0.08637,0.09587,0.10530,0.16340
compactness_mean,1138.0,0.104341,0.052790,0.01938,0.06492,0.09263,0.13040,0.34540
concavity_mean,1138.0,0.088799,0.079685,0.00000,0.02956,0.06154,0.13070,0.42680
symmetry_mean,1138.0,0.181162,0.027402,0.10600,0.16190,0.17920,0.19570,0.30400
fractal_dimension_mean,1138.0,0.062798,0.007057,0.04996,0.05770,0.06154,0.06612,0.09744

In [13]:
mu = stats['mean']
sigma = stats['std']
x = (df - mu)/sigma
x.head()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,symmetry_mean,fractal_dimension_mean
id,,,,,,,,,
842302,1.096582,-2.072424,1.269376,0.983942,1.567777,3.282072,2.651708,2.216540,2.254756
842517,1.829016,-0.353477,1.685214,1.907869,-0.826599,-0.486858,-0.023835,0.001392,-0.868271
84300903,1.579194,0.455986,1.565815,1.558199,0.941796,1.052463,1.362879,0.939272,-0.397833
84348301,-0.768571,0.253621,-0.592427,-0.764128,3.282110,3.401414,1.915055,2.866123,4.908761
84358402,1.749527,-1.151310,1.775792,1.825427,0.280249,0.539103,1.370409,-0.009556,-0.562203

In [17]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y_encoded,test_size=0.2,
                                                    random_state=42)

In [18]:
ytrain.head()

id
846226    1
92764     1
93186     0
91504     1
894329    0
Name: diagnosis, dtype: int64

# Part 3: Model Selection

### Q. Use the cheat sheet below to choose the algorithm/estimator suitable for building a model to address your candidate question(s)

* https://scikit-learn.org/stable/tutorial/machine_learning_map/

In [19]:
import numpy as np
from sklearn.linear_model import SGDClassifier # gradient descent
from sklearn.svm import SVC, LinearSVC # graph
from sklearn.naive_bayes import GaussianNB # probability
from sklearn.tree import DecisionTreeClassifier # TREE based 
from sklearn.ensemble import RandomForestClassifier 
# I need some METRICS from which i could compare these 3 algorithms and select which was better or worse
import time 
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier

In [20]:
algos = {'KNN':KNeighborsClassifier(),'RFPlain': RandomForestClassifier(),'RF5':RandomForestClassifier(n_estimators=5),'RF200':RandomForestClassifier(n_estimators=200), 'Dtree':DecisionTreeClassifier(),'SGD':SGDClassifier(), 'LinearSVC':LinearSVC(), 'SVC':SVC(), 'Sherlock':GaussianNB()}
# all algos that I want to compare 

time_all = [] 
acc_all = []
cvs_all = []

In [25]:
best_algo_acc = 0
best_model = NotImplementedError

In [26]:
for algo_name, algo in algos.items():
  start_time = time.time()
  algo.fit(xtrain, ytrain)# training
  p = algo.predict(xtest) # scoring
  acc = accuracy_score(p, ytest) #evaluation
  if acc > best_algo_acc:
    best_algo_acc = acc
    best_model = algo
  cv_score = cross_val_score(algo, xtest, ytest, cv=5)
  end_time = time.time()
  timetaken = end_time - start_time
  time_all.append(timetaken)
  acc_all.append(acc)
  cvs_all.append(cv_score)
  print('**************')
  print(algo_name)
  print("time taken = " + str(timetaken))
  print("Accuracy = " + str(acc))
  print("Cross Val Score = " + str(cv_score))

**************
KNN
time taken = 0.052477121353149414
Accuracy = 0.956140350877193
Cross Val Score = [0.91304348 0.89130435 0.95652174 0.93333333 0.86666667]
**************
RFPlain
time taken = 1.1064045429229736
Accuracy = 0.9912280701754386
Cross Val Score = [0.89130435 0.95652174 0.95652174 0.93333333 0.93333333]
**************
RF5
time taken = 0.09692025184631348
Accuracy = 0.9824561403508771
Cross Val Score = [0.91304348 0.86956522 0.93478261 0.95555556 0.95555556]
**************
RF200
time taken = 2.1815028190612793
Accuracy = 0.9912280701754386
Cross Val Score = [0.89130435 0.95652174 0.97826087 0.93333333 0.93333333]
**************
Dtree
time taken = 0.03283047676086426
Accuracy = 0.9824561403508771
Cross Val Score = [0.84782609 0.86956522 0.93478261 0.88888889 0.91111111]
**************
SGD
time taken = 0.0314631462097168
Accuracy = 0.9385964912280702
Cross Val Score = [0.89130435 0.95652174 0.95652174 0.91111111 0.95555556]
**************
LinearSVC
time taken = 0.04662179946899414
Accuracy = 0.9429824561403509
Cross Val Score = [0.89130435 0.91304348 0.95652174 0.91111111 0.95555556]
**************
SVC
time taken = 0.047164201736450195
Accuracy = 0.9605263157894737
Cross Val Score = [0.91304348 0.86956522 0.95652174 0.91111111 0.93333333]
**************
Sherlock
time taken = 0.029038190841674805
Accuracy = 0.9166666666666666
Cross Val Score = [0.89130435 0.91304348 0.97826087 0.88888889 0.93333333]

/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,

# Part 4: Model Evaluation

### Q. Identify which of the statistical measures below are suitable for the evaluation of your model.

Classification Metrics:
* Accuracy
* Precision
* Recall
* F1 Score

Regression Metrics:
    
* Mean absolute error (MAE)
* Root mean squared error (RMSE)
* Relative absolute error (RAE)
* Relative squared error (RSE)
* Mean Zero One Error (MZOE)
* Coefficient of determination

# Part 5: Stretch - Model Deployment

### Q. Evaluate the open-source app framework for Machine Learning model deployment below in your own time.

* https://streamlit.io/

In [29]:
from joblib import dump, load
dump(best_model, 'mymodel.pkl')

['mymodel.pkl']